### ISSUE TITLE
Empty statusline aftering using nvim-hardline

### ISSUE THREAD

**Issue by zchrissirhcz** [ojroques/nvim-hardline#27] opened 2021-12-04 16:49 UTC
Hi, nvim-hardline authors

I'm new to neovim, need a statueline plugin, nvim-hardline's screenshot is what I expected. I followed the steps in the readme, however, my neovim just give empty statusline. Can you please help figure out why and how to resolve this?

My init.lua is:
```lua
local fn = vim.fn
local install_path = fn.stdpath('data') .. '/site/pack/paqs/start/paq-nvim'
if fn.empty(fn.glob(install_path)) > 0 then
    fn.system({'git', 'clone', '--depth=1', 'https://github.com/savq/paq-nvim.git', install_path})
end

require 'paq' {
  {'savq/paq-nvim'},                  
  {'Mofiqul/vscode.nvim'},
  {'ojroques/nvim-hardline'},     
}

require('hardline').setup {}
```

I've executed `:PaqInstall`, and there is `nvim-hardline` repo cloned in my local cache directories. The statusline is always empty.

**Comment by ojroques** [comment] 2021-12-04 19:49
I've copy and pasted your config and the plugin works for me:

![image](https://user-images.githubusercontent.com/23409060/144722703-c9172ac1-a849-4024-a8be-976a1989419d.png)

Can you try re-installing the plugin entirely maybe? Also, what version of Neovim are you using (`nvim -v`)?

**Comment by zchrissirhcz** [comment] 2021-12-05 03:00
## nvim version
```
(base) zz@home% nvim -v
NVIM v0.7.0-dev+667-g419e0d117
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-350

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

```

## Try re-install the plugin entirly
I've just remove all the plugins installed by `Paq` except `Paq` itself. Then manually install the mentioned `vscode.nvim` and `nvim-hardline` via executing git clone command.

Then open nvim, still no status line showup.

Then I execute `:lua require('hardline').setup()` (or `:lua require('hardline').setup{}`, don't exactly remember), Then close and re-open nvim, statusline show up.

**Comment by zchrissirhcz** [comment] 2021-12-05 03:01
i.e. Now I can open nvim and automatically show correct status line:

![图片](https://user-images.githubusercontent.com/3831847/144731750-a66f0778-6caa-435f-913a-5c4e10f1900c.png)

**Comment by zchrissirhcz** [comment] 2021-12-05 03:08
I guess this might be an neovim bug, because previous, beforethe hardline works correctly, I've comment out all content in `init.lua` and deleted `init.vim`, and statusline is empty.  And now, I just again comment out `init.lua` content, but the statusline is no longer empty.

**Comment by ojroques** [comment] 2021-12-06 09:31
I've tried with your version and config but cannot reproduce... But if it works correctly now, can I close this issue or are you still having problems ?

**Closed** 2021-12-06 10:29 UTC
